# Generated by Django 5.0.3 on 2025-07-08 21:09

import django.db.models.deletion
import markup_doc.models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionValuesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acron", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ArticleDocx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True, null=True, verbose_name="Document Title"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads_docx/",
                        verbose_name="Documento",
                    ),
                ),
                ("estatus", models.IntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleDocxMarkup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True, null=True, verbose_name="Document Title"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads_docx/",
                        verbose_name="Documento",
                    ),
                ),
                ("estatus", models.IntegerField(default=0)),
                (
                    "collection",
                    models.CharField(
                        default=markup_doc.models.get_default_collection_acron,
                        max_length=10,
                    ),
                ),
                (
                    "journal_title",
                    models.TextField(
                        blank=True, null=True, verbose_name="Journal Title"
                    ),
                ),
                (
                    "acronym",
                    models.TextField(blank=True, null=True, verbose_name="Acronym"),
                ),
                (
                    "short_title",
                    models.TextField(blank=True, null=True, verbose_name="Short Title"),
                ),
                (
                    "title_nlm",
                    models.TextField(blank=True, null=True, verbose_name="NLM Title"),
                ),
                (
                    "issn",
                    models.TextField(
                        blank=True, null=True, verbose_name="ISSN (id SciELO)"
                    ),
                ),
                (
                    "pissn",
                    models.TextField(blank=True, null=True, verbose_name="Print ISSN"),
                ),
                (
                    "eissn",
                    models.TextField(
                        blank=True, null=True, verbose_name="Electronic ISSN"
                    ),
                ),
                (
                    "nimtitle",
                    models.TextField(blank=True, null=True, verbose_name="Nimtitle"),
                ),
                (
                    "pubname",
                    models.TextField(
                        blank=True, null=True, verbose_name="Publisher Name"
                    ),
                ),
                (
                    "license",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="License (URL)",
                    ),
                ),
                (
                    "vol",
                    models.IntegerField(blank=True, null=True, verbose_name="Volume"),
                ),
                (
                    "supplvol",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Suppl Volume"
                    ),
                ),
                (
                    "issue",
                    models.IntegerField(blank=True, null=True, verbose_name="Issue"),
                ),
                (
                    "supplno",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Suppl Num"
                    ),
                ),
                (
                    "issid_part",
                    models.TextField(blank=True, null=True, verbose_name="Isid Part"),
                ),
                (
                    "dateiso",
                    models.TextField(blank=True, null=True, verbose_name="Dateiso"),
                ),
                (
                    "month",
                    models.TextField(
                        blank=True, null=True, verbose_name="Month/Season"
                    ),
                ),
                (
                    "fpage",
                    models.TextField(blank=True, null=True, verbose_name="First Page"),
                ),
                ("seq", models.TextField(blank=True, null=True, verbose_name="@Seq")),
                (
                    "lpage",
                    models.TextField(blank=True, null=True, verbose_name="Last Page"),
                ),
                (
                    "elocatid",
                    models.TextField(
                        blank=True, null=True, verbose_name="Elocation ID"
                    ),
                ),
                (
                    "order",
                    models.TextField(
                        blank=True, null=True, verbose_name="Order (In TOC)"
                    ),
                ),
                (
                    "pagcount",
                    models.TextField(blank=True, null=True, verbose_name="Pag count"),
                ),
                (
                    "doctopic",
                    models.TextField(blank=True, null=True, verbose_name="Doc Topic"),
                ),
                (
                    "language",
                    models.TextField(blank=True, null=True, verbose_name="Idioma"),
                ),
                (
                    "spsversion",
                    models.TextField(blank=True, null=True, verbose_name="Sps version"),
                ),
                (
                    "artdate",
                    models.TextField(blank=True, null=True, verbose_name="Artdate"),
                ),
                (
                    "ahpdate",
                    models.TextField(blank=True, null=True, verbose_name="Ahpdate"),
                ),
                (
                    "file_xml",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="generate_xml/",
                        verbose_name="Document xml",
                    ),
                ),
                (
                    "text_xml",
                    models.TextField(blank=True, null=True, verbose_name="Text XML"),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "paragraph_with_language",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    ("<title>", "<title>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "language",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("aa", "Afar"),
                                                    ("af", "Afrikaans"),
                                                    ("ak", "Akan"),
                                                    ("sq", "Albanian"),
                                                    ("am", "Amharic"),
                                                    ("ar", "Arabic"),
                                                    ("an", "Aragonese"),
                                                    ("hy", "Armenian"),
                                                    ("as", "Assamese"),
                                                    ("av", "Avaric"),
                                                    ("ae", "Avestan"),
                                                    ("ay", "Aymara"),
                                                    ("az", "Azerbaijani"),
                                                    ("bm", "Bambara"),
                                                    ("ba", "Bashkir"),
                                                    ("eu", "Basque"),
                                                    ("be", "Belarusian"),
                                                    ("bn", "Bengali"),
                                                    ("bi", "Bislama"),
                                                    ("bs", "Bosnian"),
                                                    ("br", "Breton"),
                                                    ("bg", "Bulgarian"),
                                                    ("my", "Burmese"),
                                                    ("ca", "Catalan, Valencian"),
                                                    ("ch", "Chamorro"),
                                                    ("ce", "Chechen"),
                                                    ("ny", "Chichewa, Chewa, Nyanja"),
                                                    ("zh", "Chinese"),
                                                    (
                                                        "cu",
                                                        "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic",
                                                    ),
                                                    ("cv", "Chuvash"),
                                                    ("kw", "Cornish"),
                                                    ("co", "Corsican"),
                                                    ("cr", "Cree"),
                                                    ("hr", "Croatian"),
                                                    ("cs", "Czech"),
                                                    ("da", "Danish"),
                                                    (
                                                        "dv",
                                                        "Divehi, Dhivehi, Maldivian",
                                                    ),
                                                    ("nl", "Dutch, Flemish"),
                                                    ("dz", "Dzongkha"),
                                                    ("en", "English"),
                                                    ("eo", "Esperanto"),
                                                    ("et", "Estonian"),
                                                    ("ee", "Ewe"),
                                                    ("fo", "Faroese"),
                                                    ("fj", "Fijian"),
                                                    ("fi", "Finnish"),
                                                    ("fr", "French"),
                                                    ("fy", "Western Frisian"),
                                                    ("ff", "Fulah"),
                                                    ("gd", "Gaelic, Scottish Gaelic"),
                                                    ("gl", "Galician"),
                                                    ("lg", "Ganda"),
                                                    ("ka", "Georgian"),
                                                    ("de", "German"),
                                                    ("el", "Greek, Modern (1453–)"),
                                                    ("kl", "Kalaallisut, Greenlandic"),
                                                    ("gn", "Guarani"),
                                                    ("gu", "Gujarati"),
                                                    ("ht", "Haitian, Haitian Creole"),
                                                    ("ha", "Hausa"),
                                                    ("he", "Hebrew"),
                                                    ("hz", "Herero"),
                                                    ("hi", "Hindi"),
                                                    ("ho", "Hiri Motu"),
                                                    ("hu", "Hungarian"),
                                                    ("is", "Icelandic"),
                                                    ("io", "Ido"),
                                                    ("ig", "Igbo"),
                                                    ("id", "Indonesian"),
                                                    (
                                                        "ia",
                                                        "Interlingua (International Auxiliary Language Association)",
                                                    ),
                                                    ("ie", "Interlingue, Occidental"),
                                                    ("iu", "Inuktitut"),
                                                    ("ik", "Inupiaq"),
                                                    ("ga", "Irish"),
                                                    ("it", "Italian"),
                                                    ("ja", "Japanese"),
                                                    ("jv", "Javanese"),
                                                    ("kn", "Kannada"),
                                                    ("kr", "Kanuri"),
                                                    ("ks", "Kashmiri"),
                                                    ("kk", "Kazakh"),
                                                    ("km", "Central Khmer"),
                                                    ("ki", "Kikuyu, Gikuyu"),
                                                    ("rw", "Kinyarwanda"),
                                                    ("ky", "Kirghiz, Kyrgyz"),
                                                    ("kv", "Komi"),
                                                    ("kg", "Kongo"),
                                                    ("ko", "Korean"),
                                                    ("kj", "Kuanyama, Kwanyama"),
                                                    ("ku", "Kurdish"),
                                                    ("lo", "Lao"),
                                                    ("la", "Latin"),
                                                    ("lv", "Latvian"),
                                                    (
                                                        "li",
                                                        "Limburgan, Limburger, Limburgish",
                                                    ),
                                                    ("ln", "Lingala"),
                                                    ("lt", "Lithuanian"),
                                                    ("lu", "Luba-Katanga"),
                                                    (
                                                        "lb",
                                                        "Luxembourgish, Letzeburgesch",
                                                    ),
                                                    ("mk", "Macedonian"),
                                                    ("mg", "Malagasy"),
                                                    ("ms", "Malay"),
                                                    ("ml", "Malayalam"),
                                                    ("mt", "Maltese"),
                                                    ("gv", "Manx"),
                                                    ("mi", "Maori"),
                                                    ("mr", "Marathi"),
                                                    ("mh", "Marshallese"),
                                                    ("mn", "Mongolian"),
                                                    ("na", "Nauru"),
                                                    ("nv", "Navajo, Navaho"),
                                                    ("nd", "North Ndebele"),
                                                    ("nr", "South Ndebele"),
                                                    ("ng", "Ndonga"),
                                                    ("ne", "Nepali"),
                                                    ("no", "Norwegian"),
                                                    ("nb", "Norwegian Bokmål"),
                                                    ("nn", "Norwegian Nynorsk"),
                                                    ("ii", "Sichuan Yi, Nuosu"),
                                                    ("oc", "Occitan"),
                                                    ("oj", "Ojibwa"),
                                                    ("or", "Oriya"),
                                                    ("om", "Oromo"),
                                                    ("os", "Ossetian, Ossetic"),
                                                    ("pi", "Pali"),
                                                    ("ps", "Pashto, Pushto"),
                                                    ("fa", "Persian"),
                                                    ("pl", "Polish"),
                                                    ("pt", "Português"),
                                                    ("pa", "Punjabi, Panjabi"),
                                                    ("qu", "Quechua"),
                                                    (
                                                        "ro",
                                                        "Romanian, Moldavian, Moldovan",
                                                    ),
                                                    ("rm", "Romansh"),
                                                    ("rn", "Rundi"),
                                                    ("ru", "Russian"),
                                                    ("se", "Northern Sami"),
                                                    ("sm", "Samoan"),
                                                    ("sg", "Sango"),
                                                    ("sa", "Sanskrit"),
                                                    ("sc", "Sardinian"),
                                                    ("sr", "Serbian"),
                                                    ("sn", "Shona"),
                                                    ("sd", "Sindhi"),
                                                    ("si", "Sinhala, Sinhalese"),
                                                    ("sk", "Slovak"),
                                                    ("sl", "Slovenian"),
                                                    ("so", "Somali"),
                                                    ("st", "Southern Sotho"),
                                                    ("es", "Español"),
                                                    ("su", "Sundanese"),
                                                    ("sw", "Swahili"),
                                                    ("ss", "Swati"),
                                                    ("sv", "Swedish"),
                                                    ("tl", "Tagalog"),
                                                    ("ty", "Tahitian"),
                                                    ("tg", "Tajik"),
                                                    ("ta", "Tamil"),
                                                    ("tt", "Tatar"),
                                                    ("te", "Telugu"),
                                                    ("th", "Thai"),
                                                    ("bo", "Tibetan"),
                                                    ("ti", "Tigrinya"),
                                                    ("to", "Tonga (Tonga Islands)"),
                                                    ("ts", "Tsonga"),
                                                    ("tn", "Tswana"),
                                                    ("tr", "Turkish"),
                                                    ("tk", "Turkmen"),
                                                    ("tw", "Twi"),
                                                    ("ug", "Uighur, Uyghur"),
                                                    ("uk", "Ukrainian"),
                                                    ("ur", "Urdu"),
                                                    ("uz", "Uzbek"),
                                                    ("ve", "Venda"),
                                                    ("vi", "Vietnamese"),
                                                    ("vo", "Volapük"),
                                                    ("wa", "Walloon"),
                                                    ("cy", "Welsh"),
                                                    ("wo", "Wolof"),
                                                    ("xh", "Xhosa"),
                                                    ("yi", "Yiddish"),
                                                    ("yo", "Yoruba"),
                                                    ("za", "Zhuang, Chuang"),
                                                    ("zu", "Zulu"),
                                                ],
                                                label="Language",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Título", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    ("<title>", "<title>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "author_paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    ("<title>", "<title>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                        (
                                            "surname",
                                            wagtail.blocks.TextBlock(
                                                label="Surname", required=False
                                            ),
                                        ),
                                        (
                                            "given_names",
                                            wagtail.blocks.TextBlock(
                                                label="Given names", required=False
                                            ),
                                        ),
                                        (
                                            "orcid",
                                            wagtail.blocks.TextBlock(
                                                label="Orcid", required=False
                                            ),
                                        ),
                                        (
                                            "affid",
                                            wagtail.blocks.TextBlock(
                                                label="Aff id", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "aff_paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    ("<title>", "<title>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                        (
                                            "affid",
                                            wagtail.blocks.TextBlock(
                                                label="Aff id", required=False
                                            ),
                                        ),
                                        (
                                            "orgname",
                                            wagtail.blocks.TextBlock(
                                                label="Orgname", required=False
                                            ),
                                        ),
                                        (
                                            "orgdiv2",
                                            wagtail.blocks.TextBlock(
                                                label="Orgdiv2", required=False
                                            ),
                                        ),
                                        (
                                            "orgdiv1",
                                            wagtail.blocks.TextBlock(
                                                label="Orgdiv1", required=False
                                            ),
                                        ),
                                        (
                                            "zipcode",
                                            wagtail.blocks.TextBlock(
                                                label="Zipcode", required=False
                                            ),
                                        ),
                                        (
                                            "city",
                                            wagtail.blocks.TextBlock(
                                                label="City", required=False
                                            ),
                                        ),
                                        (
                                            "country",
                                            wagtail.blocks.TextBlock(
                                                label="Country", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "content_body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    ("<title>", "<title>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "compound_paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    ("<title>", "<title>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "text",
                                                        wagtail.blocks.TextBlock(
                                                            label="Texto"
                                                        ),
                                                    ),
                                                    (
                                                        "formula",
                                                        wagtail.blocks.TextBlock(
                                                            label="Formula"
                                                        ),
                                                    ),
                                                ],
                                                label="Contet",
                                                required=True,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    ("<title>", "<title>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "content_back",
                    wagtail.fields.StreamField(
                        [
                            (
                                "paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    ("<title>", "<title>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "ref_paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    ("<title>", "<title>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                        (
                                            "reftype",
                                            wagtail.blocks.TextBlock(
                                                label="Ref type", required=False
                                            ),
                                        ),
                                        (
                                            "refid",
                                            wagtail.blocks.TextBlock(
                                                label="Ref id", required=False
                                            ),
                                        ),
                                        (
                                            "authors",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "Author",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "surname",
                                                                    wagtail.blocks.TextBlock(
                                                                        label="Surname",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "given_names",
                                                                    wagtail.blocks.TextBlock(
                                                                        label="Given names",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    )
                                                ],
                                                label="Authors",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "date",
                                            wagtail.blocks.TextBlock(
                                                label="Data", required=False
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.TextBlock(
                                                label="Título", required=False
                                            ),
                                        ),
                                        (
                                            "source",
                                            wagtail.blocks.TextBlock(
                                                label="Origem", required=False
                                            ),
                                        ),
                                        (
                                            "vol",
                                            wagtail.blocks.TextBlock(
                                                label="Vol", required=False
                                            ),
                                        ),
                                        (
                                            "issue",
                                            wagtail.blocks.TextBlock(
                                                label="Issue", required=False
                                            ),
                                        ),
                                        (
                                            "pages",
                                            wagtail.blocks.TextBlock(
                                                label="Páginas", required=False
                                            ),
                                        ),
                                        (
                                            "doi",
                                            wagtail.blocks.TextBlock(
                                                label="DOI", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarkupXML",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("markup_doc.articledocxmarkup",),
        ),
        migrations.CreateModel(
            name="UploadDocx",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("markup_doc.articledocxmarkup",),
        ),
        migrations.CreateModel(
            name="CollectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="markup_doc.collectionvaluesmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Título"),
                ),
                (
                    "short_title",
                    models.TextField(blank=True, null=True, verbose_name="Short Title"),
                ),
                (
                    "title_nlm",
                    models.TextField(blank=True, null=True, verbose_name="NLM Title"),
                ),
                (
                    "acronym",
                    models.TextField(blank=True, null=True, verbose_name="Acronym"),
                ),
                (
                    "issn",
                    models.TextField(
                        blank=True, null=True, verbose_name="ISSN (id SciELO)"
                    ),
                ),
                (
                    "pissn",
                    models.TextField(blank=True, null=True, verbose_name="Print ISSN"),
                ),
                (
                    "eissn",
                    models.TextField(
                        blank=True, null=True, verbose_name="Electronic ISSN"
                    ),
                ),
                (
                    "pubname",
                    models.TextField(
                        blank=True, null=True, verbose_name="Publisher Name"
                    ),
                ),
            ],
            options={
                "unique_together": {("title",)},
            },
        ),
        migrations.AddField(
            model_name="articledocxmarkup",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="markup_doc.journalmodel",
            ),
        ),
    ]
