# Generated by Django 5.0.3 on 2025-04-23 17:01

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleDocx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True, null=True, verbose_name="Document Title"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads_docx/",
                        verbose_name="Documento",
                    ),
                ),
                ("estatus", models.IntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleDocxMarkup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True, null=True, verbose_name="Document Title"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads_docx/",
                        verbose_name="Documento",
                    ),
                ),
                ("estatus", models.IntegerField(default=0)),
                (
                    "file_xml",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="generate_xml/",
                        verbose_name="Document xml",
                    ),
                ),
                (
                    "text_xml",
                    models.TextField(blank=True, null=True, verbose_name="Text XML"),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "paragraph_with_language",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "language",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[],
                                                label="Language",
                                                queryset=(),
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Título", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "author_paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                        (
                                            "surname",
                                            wagtail.blocks.TextBlock(
                                                label="Surname", required=False
                                            ),
                                        ),
                                        (
                                            "given_names",
                                            wagtail.blocks.TextBlock(
                                                label="Given names", required=False
                                            ),
                                        ),
                                        (
                                            "orcid",
                                            wagtail.blocks.TextBlock(
                                                label="Orcid", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "aff_paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                        (
                                            "orgname",
                                            wagtail.blocks.TextBlock(
                                                label="Orgname", required=False
                                            ),
                                        ),
                                        (
                                            "orgdiv2",
                                            wagtail.blocks.TextBlock(
                                                label="Orgdiv2", required=False
                                            ),
                                        ),
                                        (
                                            "orgdiv1",
                                            wagtail.blocks.TextBlock(
                                                label="Orgdiv1", required=False
                                            ),
                                        ),
                                        (
                                            "zipcode",
                                            wagtail.blocks.TextBlock(
                                                label="Zipcode", required=False
                                            ),
                                        ),
                                        (
                                            "city",
                                            wagtail.blocks.TextBlock(
                                                label="City", required=False
                                            ),
                                        ),
                                        (
                                            "country",
                                            wagtail.blocks.TextBlock(
                                                label="Country", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "content_body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "compound_paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "text",
                                                        wagtail.blocks.TextBlock(
                                                            label="Texto"
                                                        ),
                                                    ),
                                                    (
                                                        "formula",
                                                        wagtail.blocks.TextBlock(
                                                            label="Formula"
                                                        ),
                                                    ),
                                                ],
                                                label="Contet",
                                                required=True,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "content_back",
                    wagtail.fields.StreamField(
                        [
                            (
                                "paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "ref_paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<abstract>", "<abstract>"),
                                                    ("<aff>", "<aff>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<fig>", "<fig>"),
                                                    ("<history>", "<history>"),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<list>", "<list>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<sub-sec>", "<sub-sec>"),
                                                    ("<subject>", "<subject>"),
                                                    ("<table>", "<table>"),
                                                    (
                                                        "<table-caption>",
                                                        "<table-caption>",
                                                    ),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<formula>", "<formula>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                        (
                                            "reftype",
                                            wagtail.blocks.TextBlock(
                                                label="Ref type", required=False
                                            ),
                                        ),
                                        (
                                            "authors",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "Author",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "surname",
                                                                    wagtail.blocks.TextBlock(
                                                                        label="Surname",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "given_names",
                                                                    wagtail.blocks.TextBlock(
                                                                        label="Given names",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    )
                                                ],
                                                label="Authors",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "date",
                                            wagtail.blocks.TextBlock(
                                                label="Data", required=False
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.TextBlock(
                                                label="Título", required=False
                                            ),
                                        ),
                                        (
                                            "source",
                                            wagtail.blocks.TextBlock(
                                                label="Origem", required=False
                                            ),
                                        ),
                                        (
                                            "vol",
                                            wagtail.blocks.TextBlock(
                                                label="Vol", required=False
                                            ),
                                        ),
                                        (
                                            "issue",
                                            wagtail.blocks.TextBlock(
                                                label="Issue", required=False
                                            ),
                                        ),
                                        (
                                            "pages",
                                            wagtail.blocks.TextBlock(
                                                label="Páginas", required=False
                                            ),
                                        ),
                                        (
                                            "doi",
                                            wagtail.blocks.TextBlock(
                                                label="DOI", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarkupXML",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("markup_doc.articledocxmarkup",),
        ),
        migrations.CreateModel(
            name="UploadDocx",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("markup_doc.articledocxmarkup",),
        ),
    ]
