# Generated by Django 5.0.3 on 2024-09-22 18:51

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleDocx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True, null=True, verbose_name="Document Title"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads_docx/",
                        verbose_name="Documento",
                    ),
                ),
                ("estatus", models.IntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleDocxMarkup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "paragraph_with_language",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<subject>", "<subject>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<aff>", "<aff>"),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<abstract>", "<abstract>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<history>", "<history>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<table>", "<table>"),
                                                    ("<fig>", "<fig>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "language",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[],
                                                label="Language",
                                                queryset=(),
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Título", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<subject>", "<subject>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<aff>", "<aff>"),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<abstract>", "<abstract>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<history>", "<history>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<table>", "<table>"),
                                                    ("<fig>", "<fig>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "content_body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<subject>", "<subject>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<aff>", "<aff>"),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<abstract>", "<abstract>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<history>", "<history>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<table>", "<table>"),
                                                    ("<fig>", "<fig>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<subject>", "<subject>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<aff>", "<aff>"),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<abstract>", "<abstract>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<history>", "<history>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<table>", "<table>"),
                                                    ("<fig>", "<fig>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "content_back",
                    wagtail.fields.StreamField(
                        [
                            (
                                "paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("<subject>", "<subject>"),
                                                    ("<article-id>", "<article-id>"),
                                                    (
                                                        "<article-title>",
                                                        "<article-title>",
                                                    ),
                                                    ("<trans-title>", "<trans-title>"),
                                                    ("<contrib>", "<contrib>"),
                                                    ("<aff>", "<aff>"),
                                                    (
                                                        "<author-notes>",
                                                        "<author-notes>",
                                                    ),
                                                    ("<abstract>", "<abstract>"),
                                                    (
                                                        "<trans-abstract>",
                                                        "<trans-abstract>",
                                                    ),
                                                    ("<kwd-group>", "<kwd-group>"),
                                                    ("<history>", "<history>"),
                                                    ("<p>", "<p>"),
                                                    ("<sec>", "<sec>"),
                                                    ("<table>", "<table>"),
                                                    ("<fig>", "<fig>"),
                                                ],
                                                label="Label",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "paragraph",
                                            wagtail.blocks.TextBlock(
                                                label="Paragraph", required=True
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
