# Generated by Django 5.0.3 on 2025-07-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LlamaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "is_local",
                    models.BooleanField(default=False, verbose_name="Use local model"),
                ),
                (
                    "name_model",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Hugging Face model name",
                    ),
                ),
                (
                    "name_file",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Model file"
                    ),
                ),
                (
                    "hf_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Hugging Face token"
                    ),
                ),
                (
                    "download_status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "No model"),
                            (2, "Downloading model"),
                            (3, "Model downloaded"),
                            (4, "Download error"),
                        ],
                        default=1,
                        verbose_name="Local model estatus",
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        blank=True,
                        help_text="Enter the AI API URL.",
                        null=True,
                        verbose_name="URL Markapi",
                    ),
                ),
                (
                    "is_gemini",
                    models.BooleanField(default=False, verbose_name="Use API Gemini"),
                ),
                (
                    "api_key_gemini",
                    models.BooleanField(default=False, verbose_name="API KEY Gemini"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
